### ISSUE TITLE
Missing plugin?

### ISSUE THREAD

**Issue by mrnoahfink** [Mentrillum/Slender-Fortress-Modified-Versions#10]
seem like there is a missing navmesh?

Unable to load plugin "navmesh-test.smx": Could not find required plugin "navmesh"

I did see a new update that deletes a navmesh.smx. do I recompile or not?

https://github.com/Kenzzer/sourcepawn-navmesh

**Comment by mrnoahfink** [comment]
I think I fixed, but when I type "sf2_enabled 1," it says an unknown command

**Comment by mrnoahfink** [comment]
compile failed. when I put in sf2.sp in compile. 
![slendererror](https://user-images.githubusercontent.com/66857858/95685731-4b9a6200-0bbf-11eb-9bb0-aa8536dbe481.jpg)

**Comment by mrnoahfink** [comment]
UPDATE: I did use sourcemod 1.11 (dev)
and seem working so I maybe misplace when I put in. I will close when I start to play my server and see if working or not.

**Comment by mrnoahfink** [comment]
Good new however 2 bad news

Good new it did run! However here bad news is that 
1) I keep lost connections when I joined and play for 5 secs (Game/Round haven't started)
2) Spamming same error
-------------
L 10/11/2020 - 23:11:42: [SM] Blaming: sf2.smx
L 10/11/2020 - 23:11:43: [SM] Call stack trace:
L 10/11/2020 - 23:11:43: [SM]   [1] Line 11105, C:\Users\nfink\OneDrive\Desktop\New folder (3)\addons\sourcemod\scripting\sf2.sp::NPCGetUniqueID
L 10/11/2020 - 23:11:43: [SM]   [2] Line 2060, C:\Users\nfink\OneDrive\Desktop\New folder (3)\addons\sourcemod\scripting\sf2.sp::OnGameFrame
L 10/11/2020 - 23:11:43: [SM] Exception reported: Not enough space on the stack
L 10/11/2020 - 23:11:43: [SM] Blaming: sf2.smx
L 10/11/2020 - 23:11:43: [SM] Call stack trace:
L 10/11/2020 - 23:11:43: [SM]   [1] Line 11105, C:\Users\nfink\OneDrive\Desktop\New folder (3)\addons\sourcemod\scripting\sf2.sp::NPCGetUniqueID
L 10/11/2020 - 23:11:43: [SM]   [2] Line 2060, C:\Users\nfink\OneDrive\Desktop\New folder (3)\addons\sourcemod\scripting\sf2.sp::OnGameFrame
L 10/11/2020 - 23:11:43: [SM] Exception reported: Not enough space on the stack
L 10/11/2020 - 23:11:43: [SM] Blaming: sf2.smx
L 10/11/2020 - 23:11:43: [SM] Call stack trace:
L 10/11/2020 - 23:11:43: [SM]   [1] Line 11105, C:\Users\nfink\OneDrive\Desktop\New folder (3)\addons\sourcemod\scripting\sf2.sp::NPCGetUniqueID
L 10/11/2020 - 23:11:43: [SM]   [2] Line 2060, C:\Users\nfink\OneDrive\Desktop\New folder (3)\addons\sourcemod\scripting\sf2.sp::OnGameFrame
L 10/11/2020 - 23:11:43: [SM] Exception reported: Not enough space on the stack
L 10/11/2020 - 23:11:43: [SM] Blaming: sf2.smx
----------------------------------------
but here sf2 logs
[2020-10-11.log](https://github.com/Mentrillum/Slender-Fortress-Modified-Versions/files/5362885/2020-10-11.log)

**Comment by Mentrillum** [comment]
If the server crashes whenever a boss spawns, grab the alternate Navmesh plugin I provided on the tutorial or AlliedModders page. As for that error, SF2M was never made for Sourcemod 1.11 yet is supported for Sourcemod 1.10, the reason in question is I'm waiting for stable builds of Sourcemod 1.11 to come out, every SF2M server uses Sourcemod 1.10 as thats what it was built for, so I recommend switching back to Sourcemod 1.10 as everything in the code looks correct.

**Comment by mrnoahfink** [comment]
Fixed! thanks! also is there an admin menu for slender fortress?

**Comment by Mentrillum** [comment]
There is an admin menu found in the server commands.

**Comment by Critical-spec** [comment]
Mentrillium, My sf2 won't load up and i also put it on the issue, I download all the plugins and upload the files from sourcemod and yet it still won't work i also try doing the Sf2_enabled 1 but it told me unknown command is there any way to fix this
?

**Comment by Critical-spec** [comment]
Yo how do you the sf2_enabled 1 thing cause it didnt worked for me @mrnoahfink

**Comment by mrnoahfink** [comment]
@Critical-spec my working just fine, but 3 version behind. Are you complie sourcemod 1.10 or 1.11?

**Comment by Critical-spec** [comment]
1.11
